### PR TITLE
Visual overhaul (Replacing Twitter's Bootstrap with Tailwind)

### LINKED ISSUE #5: Optimize for mobile devices
While the base layout already works, there are several rough edges. For example, take this screenshot:

IMG_C7B31876212E-1

* headlines are way too big
* header takes up half of the screen.
* date-dividers break as there is not enough horizontal space

And that's just one page, so there is a lot to work on. :)

### LINKED ISSUE #24: Reconsider crosslinks between sections
Currently, all sections have persistent crosslinks in the right header part that direct the readers towards other parts of the site:

Screen Shot 2020-11-15 at 18 19 56
Screen Shot 2020-11-15 at 18 16 03
Screen Shot 2020-11-15 at 18 16 07
Screen Shot 2020-11-15 at 18 16 15

The idea is, in principle, good. However, it takes up a lot of space in the header, and reduces the amount of actual navigation items we can place. Also, in some cases, this already breaks for smaller, but not yet mobile, viewports:

Screen Shot 2020-11-15 at 18 16 36

I like the large CTA button, but maybe we can rethink this a bit to still have some form of crosslinks available, while not eating up the entire header. Maybe a dropdown-thingy?

### PR DESCRIPTION
**Pull request by skyschub**
Disclaimer: This PR is huge - and **I'm not asking for code review**. Instead, I'm just asking for last-minute blockers on the visual/content layout aspects.

While trying to address issues like #24 or #5, I have become increasingly frustrated with Bootstrap as it severely locked me out of some layout flexibility. Since I want to make sure the new site is an improvement over what we have right now, I did not want to compromise on things like #24, where we discussed an important aspect that's currently very lacking: directing users between the "project site", install guides, and "the wiki".

Luckily, my work there overlapped with the release of [Tailwind CSS](https://tailwindcss.com/) v2, and I immediately started to rebuild the site using it, completely getting rid of Bootstrap in the process. Not only does this get us a lot smaller production footprint (compared to the current project site, compressed CSS is down from 20.72 KiB to 7.57 KiB; JS is down from 41.26 KiB to 27.41 KiB, most of which is Handlebars.js, which I will remove at a future point), it also allows for much more flexible content layout options, as you can build pretty much everything inside the markdown pages itself using Tailwind's Utility classes. But that's a technical detail not relevant to most people. :)

I have deployed the preview branch to the preview setup. You can have a look at the proposed state at https://diaspora.software/ (username: `northstar`, password: `kitten`).

For reference, here are some screenshots as well:

* [Project site index page example](https://user-images.githubusercontent.com/344777/102955137-7d8c4680-44d5-11eb-8766-86694f1fe3e3.png)
* [Blog overview](https://user-images.githubusercontent.com/344777/102955158-8da42600-44d5-11eb-9bec-a2c602b1e9de.png)
* [Blog post list](https://user-images.githubusercontent.com/344777/102955176-972d8e00-44d5-11eb-8acf-027c85ba539c.png)
* [Guides overview](https://user-images.githubusercontent.com/344777/102955182-9f85c900-44d5-11eb-81f2-98702e9d2a03.png)
* [Guide list](https://user-images.githubusercontent.com/344777/102955197-a90f3100-44d5-11eb-98d5-ef8af94d9be5.png)
* [Installation overview](https://user-images.githubusercontent.com/344777/102955310-e247a100-44d5-11eb-84f8-22e327e5ebec.png)
* [Installation version selector](https://user-images.githubusercontent.com/344777/102955312-e2e03780-44d5-11eb-8410-2c89b50ac631.png)
* [Installation step](https://user-images.githubusercontent.com/344777/102955314-e378ce00-44d5-11eb-946a-0e1a8c246da6.png)
* [Update guide overview](https://user-images.githubusercontent.com/344777/102955348-fa1f2500-44d5-11eb-9ab1-9c978744a5dc.png)
* [Reference page containing most available content style blocks](https://user-images.githubusercontent.com/344777/102955365-05725080-44d6-11eb-9b97-9abd24c0576c.png)
* [Mobile: Project site overviiew](https://user-images.githubusercontent.com/344777/102955410-1de26b00-44d6-11eb-9d8a-aa93e02cc56b.png)
* [Mobile: Example mobile menu](https://user-images.githubusercontent.com/344777/102955409-1d49d480-44d6-11eb-89f9-94b5e35a7e3f.png)
* [Mobile: Blog overview](https://user-images.githubusercontent.com/344777/102955404-1b801100-44d6-11eb-94cc-62babd6355d2.png)
* [Mobile: Blog list](https://user-images.githubusercontent.com/344777/102955405-1cb13e00-44d6-11eb-8f02-9827926ab67c.png)
* [Mobile: Installation overview](https://user-images.githubusercontent.com/344777/102955408-1d49d480-44d6-11eb-8b66-fbc353af0e33.png)

You'll notice a few changes over the current layout:

* Most notable, I added some green - mainly because I got sick of our continued gray on grey. ;)
* You'll also notice that a lot of things are underlined now - that's not a mistake, and even though I think it adds a bit of visual noise, I learned that always underlining links in the content area is a good thing for accessibility reasons, so there we go. 
* Everything should work fine on mobile devices now. There are some rough edges, but that's expected for some sections (like code-blocks, ..) but overall, this is much better than what we had before.

So, I invite you to look over those things and let me know if you have any strong opinions and would like to have something to change. Notice that I fully intend on merging this soon, even if I receive 🦗s, because in the end, done is better than perfect - and I'm already two years behind the initially visioned timeline of this project. :)

🌈

### CODE REVIEW

**Comment by Flaburgan** [comment]
Hello Dennis, and thank you for your work!
Today isn't the day I'm the most available for having a look obviously, but here is some quick feedback:
- We don't exactly get what the sub menu is referring to. The link in the top all bring you to different places (subdomains), the sub menu allows you to navigate in the pages of the current places. I was wondering if its background color shouldn't be different. I think that to understand well where we are, it should at least have a "Home" link at the left of the "Get involved" link, which would be bottom bordered.
- the underline inside the "Find out more" buttons feels weird, maybe that's part of "You'll also notice that a lot of things are underlined now" but IMO in the buttons it isn't necessary
- +1 to add colors, being green or others. Only grey isn't great, so more green is cool.

I will try to think more about it after Christmas and maybe do some propositions.

**Comment by skyschub** [comment]
> We don't exactly get what the sub menu is referring to.

Who exactly is "we" here? I'm specifically asking, since this has been in discussion for more than a month (see #24), and I've passed this through three non-technical folks using diaspora\* (no other involvement with the project) and there appeared to be no problem whatsoever. I'm curios to know what the issue here is.

I strongly disagree that there should be a "home" link. They actually make no sense (what even is "home"? what would it be if you're inside the blog section? wouldn't you expect a "home" link to get you to the project overview index site?) - and it's a widely used pattern to click the "root menu" item - or the logo - to get to the "home" page.

Is this something you *think* might be an issue, or did you observe someone actually having an issue with the navigation? Really curios here.

> the underline inside the "Find out more" buttons feels weird

I'm on the fence here. I have removed the underlines for buttons now, and I'll keep it that way until someone yells at me. Thanks for the feedback.

> Only grey isn't great, so more green is cool.

There also is a sneaky rainbow! :p

**Comment by jhass** [comment]
Too much to review for me currently, but you have my trust on this! :+1:

**Comment by skyschub** [comment]
I'll merge this this Friday -- if anyone has important opinions to add, please do so now. However, don't worry if you're too busy or don't have the brain power at the moment, we can always improve and refine things as we go, obviously. :)

**Comment by goobertron** [comment]
Sorry I didn't manage to comment on this before. I've only been able to scan the pages, and I'm happy with what I've seen.

– I like the addition of another colour.
– My only negative comment is that the new icons for Decentralization, Freedom and Privacy are rather flat and boring. But 'flat' seems to be the thing these days, and if it's only me (old fart that I am) that isn't keen, that's fine.
– I *definitely* approve of the picture of a kitten. If this doesn't stay I will be very cross.

Thanks for doing all this work, @denschub. The project site will be greatly improved as a result.

**Comment by goobertron** [comment]
Sorry I didn't manage to comment on this before. I've only been able to scan the pages, and I'm happy with what I've seen.

– I like the addition of another colour.
– My only negative comment is that the new icons for Decentralization, Freedom and Privacy are rather flat and boring. But 'flat' seems to be the thing these days, and if it's only me (old fart that I am) that isn't keen, that's fine.
– I *definitely* approve of the picture of a kitten. If this doesn't stay I will be very cross.

Thanks for doing all this work, @denschub. The project site will be greatly improved as a result.

**Comment by skyschub** [comment]
Appreciate the feedback.

I do agree with the icons, actually. Early in this work, I actually played around with a implementation that makes the icons a bit less flat by adding a subtle gradient. Unfortunately, web development is horrible and it broke in Safari (both Desktop and Mobile), [so I had to remove it](https://github.com/diaspora/north-star/pull/26/commits/62702ba344abdb06d2e1b999e4e8dd4b7b2117a4). With that implementation, the icons would look like this (my idea on top, current state below as a comparison):

Screenshot 2021-01-21 at 18 03 19

Maybe the effect is too subtle for some displays, but I kinda like how it makes them look less flat. What do you think about that, @goobertron? Too subtle? Great idea and worth trying to fix in Safari? Kinda nice but maybe not worth some extra hours of work? :)

As for the kitten... well. I can promise you that Mr. Abdoun will continue looking very sadly on the 404 page. The current kitten that's placed in the content probably won't stay there, that's all just placeholder contents for now - but I can hide a sneaky little kitten where we talk about Markdown syntax, and embedding pictures. ;)

**Comment by SuperTux88** [comment]
I like the gradient. What exactly broke on Safari? Did it just not work (so looking like now with it removed) or was it completely broken so it broke more things?

**Comment by skyschub** [comment]
Because WebKit [can't `background-clip: text;` inside Flexbox](https://bugs.webkit.org/show_bug.cgi?id=169125). Why? Who knows. Clearly a bug. This results in the icon just being invisible, which isn't awesome. Most likely I can work around that, though, will give it a shot.

**Comment by skyschub** [comment]
Found a workaround, slight gradient is back, and it works everywhere (including Safari on macOS and iOS).

**Comment by skyschub** [comment]
I merged this, so that I can focus on content creation and stuff. But please feel free to raise follow-up issues if anyone wants anything changed.

**Pull request merged**
